server:
  port:8080

spring:
  datasource:
    name: mytest
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mytest?
      username: root
      password: root
#      initial-size: 1
#      min-idle: 1
#      max-active: 20
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validdation-query: select 'x'
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: false
#      max-open-prepared-statement-per-connection-size: 20

mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath*:tk/**/mapper/*.xml
  type-aliases-package: com.example.springbootdemo2.model

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql